IIG School/IIG School/Areas/Admin/Controllers/ExamResultController.cs
using IIG_School.Data;
using IIG_School.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using  IIG_School.Helpers;
using System.Globalization;

namespace IIG_School.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    [Authorize(Roles = Constants.Roles.Admin)]
    public class ExamResultController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ExamResultController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IFormFile file)
        {
            using (var package = new ExcelPackage(file.OpenReadStream()))
            {
                var worksheet = package.Workbook.Worksheets[0]; // assuming your data is on the first worksheet
                List<ExcelDataModel> lst = new();
                for (int row = 2; row <= worksheet.Dimension.End.Row; row++)
                {
                    var data = new ExcelDataModel
                    {
                        ExamName = worksheet.Cells[row, 2].GetValue<string>(),
                        ExamDate = DateTime.ParseExact(worksheet.Cells[row, 3].GetValue<string>(), "dd/MM/yyyy", CultureInfo.InvariantCulture),
                        ExamTime = worksheet.Cells[row, 4].GetValue<string>(),
                        Location = worksheet.Cells[row, 5].GetValue<string>(),
                        Note = worksheet.Cells[row, 6].GetValue<string>()
                    };

                    lst.Add(data);
                }
                await _context.ExcelDataModels!.AddRangeAsync(lst);
                _context.SaveChanges();
            }

            return RedirectToAction("Index", "HomeAdmin");
        }
    } 
}

IIG School/IIG School/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IIG_School.Data;
using IIG_School.Models;
using IIG_School.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using IIG_School.Helpers;
using Newtonsoft.Json;
using System.Globalization;
using Microsoft.AspNetCore.Identity;
using OfficeOpenXml.Style;

namespace IIG_School.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    [Authorize(Roles = Constants.Roles.Admin)]
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }
        // GET: Admin/Products
        public async Task<IActionResult> Index()
        {
            return View(await _productService.GetList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile upload)
        {
            try
            {
                await _productService.Add(product, upload);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
            }
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _productService.GetAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product, IFormFile upload)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            try
            {
                await _productService.Update(product, upload);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

            }
            return View(product);
        }

        // GET: Admin/Products/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productService.GetAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _productService.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message.ToString());
            }
            return NotFound();
        }
      
    }
}

IIG School/IIG School/Areas/Admin/Views/Shared/_Footer.cshtml
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; 2023 - IIG School - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

IIG School/IIG School/Areas/Admin/Views/Shared/_Header.cshtml
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a asp-action="Index" asp-area="" asp-controller="Home" class="logo d-flex align-items-center">
            <img src="~/AdminLayout/img/logo.png" alt="">
            <span class="d-none d-lg-block">IIG School</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number">4</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        You have 4 new notifications
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-exclamation-circle text-warning"></i>
                        <div>
                            <h4>Lorem Ipsum</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>30 min. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-x-circle text-danger"></i>
                        <div>
                            <h4>Atque rerum nesciunt</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>1 hr. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-check-circle text-success"></i>
                        <div>
                            <h4>Sit rerum fuga</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>2 hrs. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-info-circle text-primary"></i>
                        <div>
                            <h4>Dicta reprehenderit</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>4 hrs. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li class="dropdown-footer">
                        <a href="#">Show all notifications</a>
                    </li>

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->
            <partial name="_LoginPartial" />
        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

IIG School/IIG School/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @{
        await Html.RenderPartialAsync("_Meta");
        await Html.RenderPartialAsync("_Style");
    }
</head>
<body>
    @{
        await Html.RenderPartialAsync("_Header");
        await Html.RenderPartialAsync("_SlideBar");
    }
    <main id="main" class="main">
        @RenderBody()
    </main>
    @{
        await Html.RenderPartialAsync("_Footer");
    }
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IIG School/IIG School/Areas/Admin/Views/Shared/_Meta.cshtml
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">

<title>@ViewData["Title"] - Admin IIG_School</title>
<meta content="" name="description">
<meta content="" name="keywords">

<!-- Favicons -->
<link href="~/AdminLayout/img/favicon.png" rel="icon">
<link href="~/AdminLayout/img/apple-touch-icon.png" rel="apple-touch-icon">

IIG School/IIG School/Areas/Admin/Views/Shared/_SlideBar.cshtml
@using IIG_School.Helpers;
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link @ManageMenuPage.MainNavClass(ViewContext, "HomeAdmin")" asp-area="Admin" asp-action="Idnex" asp-controller="HomeAdmin">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-heading">Sản Phẩm</li>

        <li class="nav-item">
            <a class="nav-link @ManageMenuPage.MainNavClass(ViewContext, "Product", "Index")" asp-action="Index" asp-area="Admin" asp-controller="Products">
                <i class="bi bi-person"></i>
                <span>Sản Phẩm</span>
            </a>
        </li><!-- End Profile Page Nav -->
        <li class="nav-heading">Câu Hỏi</li>

        <li class="nav-item">
            <a class="nav-link @ManageMenuPage.MainNavClass(ViewContext, "Question", "Create")" asp-action="Create" asp-area="Admin" asp-controller="ExamResult">
                <i class="bi bi-question-circle"></i>
                <span>Dữ liệu kết quả thi</span>
            </a>
        </li>

    </ul>

</aside><!-- End Sidebar-->

IIG School/IIG School/Areas/Admin/Views/Shared/_Style.cshtml
  <!-- Google Fonts -->
  <l  ink href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/AdminLayout/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/AdminLayout/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/AdminLayout/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/AdminLayout/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/AdminLayout/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/AdminLayout/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/AdminLayout/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/AdminLayout/css/style.css" rel="stylesheet">