IIG School/IIG School/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace IIG_School.Models
{
    public class Product : IEntityBase
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [DisplayName("Tên sản phẩm")]
        public string? ProductName { get; set; }

        [Required]
        [DisplayName("Mô tả sản phẩm")]
        public string? ProductDescription { get; set; }


        [Required]
        [DisplayName("Giá sản phẩm")]
        public double ProductPrice { get; set; }

        [DisplayName("Giảm giá sản phẩm")]
        public double ProductSale { get; set; }

        [Required]
        [DisplayName("Số lượng tồn kho")]
        public int Inventory { get; set; }

        [DisplayName("Name Image")]
        public string? ImageName { get; set; }
        [DisplayName("Upload File")]
        public string? ImagePath { get; set; }
    }
}

IIG School/IIG School/Areas/Admin/Controllers/HomeAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using IIG_School.Helpers;

namespace IIG_School.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin")]
    [Route("Admin/homeadmin")]
    [Authorize]
    [Authorize(Roles = Constants.Roles.Admin)]
    public class HomeAdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

IIG School/IIG School/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IIG_School.Data;
using IIG_School.Models;
using IIG_School.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using IIG_School.Helpers;
using Newtonsoft.Json;
using System.Globalization;
using Microsoft.AspNetCore.Identity;
using OfficeOpenXml.Style;

namespace IIG_School.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    [Authorize(Roles = Constants.Roles.Admin)]
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }
        // GET: Admin/Products
        public async Task<IActionResult> Index()
        {
            return View(await _productService.GetList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile upload)
        {
            try
            {
                await _productService.Add(product, upload);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
            }
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _productService.GetAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product, IFormFile upload)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            try
            {
                await _productService.Update(product, upload);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

            }
            return View(product);
        }

        // GET: Admin/Products/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productService.GetAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _productService.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message.ToString());
            }
            return NotFound();
        }
      
    }
}

IIG School/IIG School/Controllers/ProductController.cs
using IIG_School.Data;
using IIG_School.Models;
using IIG_School.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace IIG_School.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IOrderService _orderService;
        public ProductController (IProductService productService, UserManager<ApplicationUser> userManager,
            IOrderService orderService)
        {
            _productService = productService;
            _userManager = userManager;
            _orderService = orderService;
        }
        public const string CARTKEY = "cart";

        public async Task<IActionResult> Index()
        {
            var lst = await _productService.GetList();
            return View(lst);
        }

        public async Task<IActionResult> Detail(int Id)
        {
            var product = await _productService.GetAsync(Id);
            if (product == null) return NotFound();
            return View(product);
        }

        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            order.UserId = userId;

            var cart = GetCartItems();

            if (cart.Count == 0)
            {
                ModelState.AddModelError("", "Giỏ hàng trống");
            }

            if (ModelState.IsValid)
            {
                var OrderID = await _orderService.Add(order, cart);
                ClearCart();
                return RedirectToAction("Confirm", "Order", new {Id = OrderID});
            }

            return View(order);
        }

        [Authorize]
        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = $"Cảm ơn bạn đã đặt hàng, chúng tôi sẽ giao hàng cho bạn sớm nhất!";
            return View();
        }

        [Route("/cart", Name = "cart")]
        public IActionResult Cart()
        {
            return View(GetCartItems());
        }

        [Route("addcart/{productid:int}", Name = "addcart")]
        public IActionResult AddToCart([FromRoute] int productid, string returnUrl, int quantity = 1, int size = 35)//size mặc định 35
        {

            var product = _productService.Get(productid);
            if (product == null)
                return NotFound("Không có sản phẩm");

            // Xử lý đưa vào Cart ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == productid);
            if (cartitem != null)
            {
                cartitem.quantity += quantity;
            }
            else
            {
                cart.Add(new CartItem() { quantity = quantity, product = product});
            }

            SaveCartSession(cart);
            return Redirect(returnUrl);
        }

        List<CartItem> GetCartItems()
        {

            var session = HttpContext.Session;
            string jsoncart = session.GetString(CARTKEY);
            if (jsoncart != null)
            {
                return JsonConvert.DeserializeObject<List<CartItem>>(jsoncart);
            }
            return new List<CartItem>();
        }

        [Route("/updatecart", Name = "updatecart")]
        [HttpPost]
        public IActionResult UpdateCart([FromForm] int productid, [FromForm] int quantity)
        {
            // Cập nhật Cart thay đổi số lượng quantity ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.quantity = quantity;
            }
            SaveCartSession(cart);
            // Trả về mã thành công (không có nội dung gì - chỉ để Ajax gọi)
            return Ok();
        }

        [Route("/removecart/{productid:int}", Name = "removecart")]
        public IActionResult RemoveCart([FromRoute] int productid, string returnUrl)
        {
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.product.Id == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cart.Remove(cartitem);
            }

            SaveCartSession(cart);
            return Redirect(returnUrl);
        }

        void ClearCart()
        {
            var session = HttpContext.Session;
            session.Remove(CARTKEY);
        }

        // Lưu Cart (Danh sách CartItem) vào session
        void SaveCartSession(List<CartItem> ls)
        {
            var session = HttpContext.Session;
            string jsoncart = JsonConvert.SerializeObject(ls);
            session.SetString(CARTKEY, jsoncart);
        }

    }
}

IIG School/IIG School/Areas/Admin/Views/Products/Create.cshtml
@model IIG_School.Models.Product

@{
    ViewData["Title"] = "Tạo Sản Phẩm";
}

<div class="pagetitle">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="HomeAdmin">Home</a></li>
            <li class="breadcrumb-item active">@ViewData["Title"]</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<section class="section dashboard">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="ProductName" class="control-label"></label>
                    <input asp-for="ProductName" class="form-control" />
                    <span asp-validation-for="ProductName" class="text-danger"></span>
                </div>
                
                <div class="form-group mt-2">
                    <label asp-for="ProductDescription" class="control-label"></label>
                    <textarea asp-for="ProductDescription" id="editor1" class="editor" cols="30" rows="10"></textarea>
                    <span asp-validation-for="ProductDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProductPrice" class="control-label"></label>
                    <input asp-for="ProductPrice" class="form-control" />
                    <span asp-validation-for="ProductPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProductSale" class="control-label"></label>
                    <input asp-for="ProductSale" class="form-control" />
                    <span asp-validation-for="ProductSale" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Inventory" class="control-label"></label>
                    <input asp-for="Inventory" class="form-control" />
                    <span asp-validation-for="Inventory" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <img id="uploadedImage" src="#" alt="Uploaded Image" accept="image/png, image/jpeg" style="display:none; width:200px">
                </div>
                <div class="form-group my-2">
                    <label for="upload" class="control-label">Upload Image</label>
                    <input type="file" name="upload" accept="image/*" id=readUrl />
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</section>

IIG School/IIG School/Areas/Admin/Views/Products/Delete.cshtml
@model IIG_School.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductSale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductSale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inventory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inventory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IIG School/IIG School/Areas/Admin/Views/Products/Details.cshtml
@model IIG_School.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductSale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductSale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inventory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inventory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IIG School/IIG School/Areas/Admin/Views/Products/Edit.cshtml
@model IIG_School.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<div class="pagetitle">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="HomeAdmin">Home</a></li>
            <li class="breadcrumb-item active">@ViewData["Title"]</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<section class="section dashboard">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="ProductName" class="control-label"></label>
                    <input asp-for="ProductName" class="form-control" />
                    <span asp-validation-for="ProductName" class="text-danger"></span>
                </div>

                <div class="form-group mt-2">
                    <label asp-for="ProductDescription" class="control-label"></label>
                    <textarea asp-for="ProductDescription" id="editor1" class="editor" cols="30" rows="10"></textarea>
                    <span asp-validation-for="ProductDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProductPrice" class="control-label"></label>
                    <input asp-for="ProductPrice" class="form-control" />
                    <span asp-validation-for="ProductPrice" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProductSale" class="control-label"></label>
                    <input asp-for="ProductSale" class="form-control" />
                    <span asp-validation-for="ProductSale" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Inventory" class="control-label"></label>
                    <input asp-for="Inventory" class="form-control" />
                    <span asp-validation-for="Inventory" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <img id="uploadedImage" src="#" alt="Uploaded Image" accept="image/png, image/jpeg" style="display:none; width:200px">
                </div>
                <div class="form-group my-2">
                    <label for="upload" class="control-label">Upload Image</label>
                    <input type="file" name="upload" accept="image/*" id=readUrl />
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</section>

IIG School/IIG School/Areas/Admin/Views/Products/Index.cshtml
@model IEnumerable<IIG_School.Models.Product>

@{
    ViewData["Title"] = "Danh sách sản phẩm";
}

<div class="pagetitle">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="HomeAdmin">Home</a></li>
            <li class="breadcrumb-item active">@ViewData["Title"]</li>
        </ol>
        <a asp-controller="Products" asp-action="Create" class="btn btn-primary">Create</a>
    </nav>
</div><!-- End Page Title -->
<section class="section dashboard">
    <div class="row">
        <!-- Top Selling -->
        <div class="col-12">
            <div class="card top-selling overflow-auto">

                <div class="filter">
                    <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                        <li class="dropdown-header text-start">
                            <h6>Filter</h6>
                        </li>

                        <li><a class="dropdown-item" href="#">Today</a></li>
                        <li><a class="dropdown-item" href="#">This Month</a></li>
                        <li><a class="dropdown-item" href="#">This Year</a></li>
                    </ul>
                </div>

                <div class="card-body pb-0">
                    <h5 class="card-title">Top Selling <span>| Today</span></h5>

                    <table class="table table-borderless datatable">
                        <thead>
                            <tr>
                                <th scope="col">Preview</th>
                                <th scope="col">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Sale</th>
                                <th scope="col">Ammount</th>
                                <th scope="col">Revenue</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model) {
                                <tr>
                                <th scope="row"><a href="#">
                                    <img src="~/Image/@Html.DisplayFor(modelItem => item.ImageName)" alt="Uploaded Image" accept="image/png, image/jpeg"/>
                                </th>
                                <td><a href="#" class="text-primary fw-bold">@Html.DisplayFor(modelItem => item.ProductName)</a></td>
                                <td>$@item.ProductPrice</td>
                                <td>@item.ProductSale</td>
                                <td class="fw-bold">@Html.DisplayFor(modelItem => item.Inventory)</td>
                                <td>$@(item.ProductPrice - item.ProductSale)</td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- End Top Selling -->
    </div>
</section>